config/routes.rb
Rails.application.routes.draw do
  get "health" => "health#index"

  # Add application specific routes under here
  #-----------------------------------------------------------------------------
  root "home#index"

  # Help
  get "help" => "help#index", as: :help

  # Sessions
  get "login"  => "sessions#login",  as: :login
  get "logout" => "sessions#logout", as: :logout

  # Users
  get "sign-up" => "users#new", as: :new_user

  resources :backend_apps, path: "apps" do
    resources :components, controller: :backend_app_components,
                           only: %i(create destroy index new show)
    resources :features, only: %i(create new)
    resources :models do
      member do
        post :remove_column, path: "remove-column"
      end
    end

    member do
      get :documentation
      get :status
    end
  end
  resources :sessions, only: %i(create)
  resources :users,    only: %i(create edit update)
end

app/controllers/backend_app_components_controller.rb
class BackendAppComponentsController < ApplicationController
  include BackendAppFindable

  before_action :require_login
  before_action :find_app
  before_action :find_component, only: %i(destroy show)

  def create
    component = Component.find_by id: params[:component_id]
    @app.add_component component
    flash[:success] = "Component added"
    redirect_to backend_app_components_path @app
  end

  def destroy
    @app.remove_component @component
    flash[:notice] = "Component removed"
    redirect_to backend_app_components_path @app
  end

  def index
    @components = include_subcomponents @app.components.order(name: :asc)
  end

  def new
    component_ids = @app.components.select(%i(id)).map(&:id)
    @components = include_subcomponents(
      Component.where.not(id: component_ids).order(name: :asc)
    )
  end

  def show
    @component     = @app.components.find_by id: params[:id]
    @subcomponents = @component.components
    @components    = @subcomponents + [@component]
  end

  private

  def backend_app_id_key
    :backend_app_id
  end

  def find_component
    @component = @app.components.find_by id: params[:id]
    if @component.nil?
      flash[:notice] = "Component not found"
      redirect_to backend_app_components_path @app
    end
  end

  def include_subcomponents(collection)
    collection.map { |c| [c, c.components].compact }
  end
end

app/views/backend_app_components/index.html.haml
= content_for :page_title, "Components"

.content__body
  %h3
    = render "backend_apps/shared/breadcrumbs"
    Components
  %p
    Add a
    = link_to "new component", new_backend_app_component_path(@app)
  .content__body__list
    %ul{ type: "circle" }
      - @components.each do |component, components|
        %li
          %p
            = link_to component.name,
              backend_app_component_path(@app, component)
          = form_tag backend_app_component_path(@app, component),
            method: :delete do
            = button_tag "Remove component"
        - components.each do |comp|
          %li
            %p
              = comp.name
              \-
              %i
                subcomponent of
                = link_to component.name,
                  backend_app_component_path(@app, component)

app/views/backend_app_components/new.html.haml
= content_for :page_title, "Add Component"

.content__body
  %h3
    = render "backend_apps/shared/breadcrumbs"
    = link_to "Components", backend_app_components_path(@app)
    \-
    Add Component
  %p
    Select a component and add it to your app
  .content__body__list
    %ul{ type: "circle" }
      - @components.each do |component, components|
        %li
          %p
            = component.name
            \-
            %i
              = component.description
            = form_tag backend_app_components_path(@app) do
              = hidden_field_tag :component_id, component.id
              = button_tag "Add component"
          - components.each do |comp|
            %p
              \-
              = comp.name
              \-
              %i
                = comp.description

app/views/backend_app_components/show.html.haml
= content_for :page_title, @component.name

.content__body
  %h3
    = render "backend_apps/shared/breadcrumbs"
    = link_to "Components", backend_app_components_path(@app)
    \-
    = @component.name
  %p
    = @component.description
.content__body
  %h4
    Models
  - @components.each do |component|
    - component.models.each do |name, schema|
      %p
        = name
      %table
        %tr
          %td
            %p
              Column name
          %td
            %p
              Data type
          %td
            %p
              Required
          %td
            %p
              Relationship to
        - schema.each do |column, hash|
          %tr
            %td
              %p
                = column
            %td
              %p
                = hash["type"]
            %td
              %p
                = hash["required"]
            %td
              %p
                = hash["relationship_to"]
- if @subcomponents.present?
  .content__body
    %h4
      Subcomponents
    .content__body__list
      %ul{ type: "circle" }
        - @subcomponents.each do |component|
          %li
            %p
              = component.name