config/routes.rb
Rails.application.routes.draw do
  get "health" => "health#index"

  # Add application specific routes under here
  #-----------------------------------------------------------------------------
  root "home#index"

  # Help
  get "help" => "help#index", as: :help

  # Sessions
  get "login"  => "sessions#login",  as: :login
  get "logout" => "sessions#logout", as: :logout

  # Users
  get "sign-up" => "users#new", as: :new_user

  resources :backend_apps, path: "apps" do
    resources :components, controller: :backend_app_components,
                           only: %i(create destroy index new show)
    resources :features, only: %i(create new)
    resources :models do
      member do
        post :remove_column, path: "remove-column"
      end
    end

    member do
      get :documentation
      get :status
    end
  end
  resources :sessions, only: %i(create)
  resources :users,    only: %i(create edit update)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index/_about.html.haml
%section.about
  .section__content
    %h4
      We make it simple for you to build and
      launch your application.

app/views/home/index/_definition.html.haml
= content_for :definition_section_content do
  .section__content
    %h2
      What is an
      <span>Application</span>?
    %p
      Your application allows users to interact with your service or product
      from their laptop and mobile devices.

%section.definition
  .section__pattern
    = yield :definition_section_content
  = yield :definition_section_content

app/views/home/index/_features.html.haml
%section.features
  .section__content
    %h2
      Zero to one hundred
    .steps
      .step
        .step__body
          .step__body__image
            %i.fa.fa-magic
          .step__body__title
            %h4
              Zero code
          .step__body__text
            %p
              Our tool is ultra
              %span
                simple
              so that you will never have to write a single line of code
      .step
        .step__body
          .step__body__image
            %i.fa.fa-cogs
          .step__body__title
            %h4
              Customizable
          .step__body__text
            %p
              Make anything your business requires and as fast as you need,
              you hold all the
              %span
                power
      .step
        .step__body
          .step__body__image
            %i.fa.fa-shield
          .step__body__title
            %h4
              Dependable
          .step__body__text
            %p
              Never worry because we host, test, maintain, and document
              %span
                everything
              for you
    .clear

app/views/home/index/_hero.html.haml
.hero
  .hero__background
    .hero__background__tint
    .hero__background__image
    .hero__background__content
      .hero__background__content__image
        = image_tag "logo.png"
      .hero__background__content__text
        %h1
          Firebot starts you up
      .hero__background__content__actions
        = link_to "Get started", "#", class: "js-button js-scroll-to",
          data: { "scroll-to-key" => "get-started" }

app/views/home/index/_start.html.haml
= content_for :start_section_content do
  .section__content
    %h2
      Get started now
    %div
      - if logged_in?
        .section__content__action
          = link_to "View apps", backend_apps_path,
            class: "form__button--blue form__button--medium left"
        .section__content__action
          = link_to "Create app", new_backend_app_path,
            class: "form__button--medium right"
      - else
        .section__content__action
          = link_to "Login", login_path,
            class: "form__button--blue form__button--medium left"
        .section__content__action
          = link_to "Sign up", new_user_path,
            class: "form__button--medium right"
    .clear

%section.start.get-started
  .section__pattern
    = yield :start_section_content
  = yield :start_section_content