config/routes.rb
Rails.application.routes.draw do
  get "health" => "health#index"

  # Add application specific routes under here
  #-----------------------------------------------------------------------------
  root "home#index"

  # Help
  get "help" => "help#index", as: :help

  # Sessions
  get "login"  => "sessions#login",  as: :login
  get "logout" => "sessions#logout", as: :logout

  # Users
  get "sign-up" => "users#new", as: :new_user

  resources :backend_apps, path: "apps" do
    resources :components, controller: :backend_app_components,
                           only: %i(create destroy index new show)
    resources :features, only: %i(create new)
    resources :models do
      member do
        post :remove_column, path: "remove-column"
      end
    end

    member do
      get :documentation
      get :status
    end
  end
  resources :sessions, only: %i(create)
  resources :users,    only: %i(create edit update)
end

app/models/backend_app.rb
class BackendApp < ActiveRecord::Base
  with_options dependent: :destroy do
    has_many :access_tokens, as: :tokenable
    has_many :compositions, -> { where composable_type: "BackendApp" },
                            foreign_key: :composable_id
    has_many :features, as: :loggable
    has_many :logs, as: :loggable
    has_many :models
  end

  has_many :components, through: :compositions

  belongs_to :user

  validates_presence_of :name, :user
  validates_uniqueness_of :name, scope: :user_id

  before_create :set_uid

  def add_component(component)
    composition = Composition.new component: component, composable: self
    add_models_from_component(component, composition) if composition.save
  end

  def components_count
    count_all_components components
  end

  def remove_component(component)
    composition = compositions.find_by component_id: component.id
    composition.models.each do |model|
      model.destroy
    end
    composition.destroy
  end

  private

  def add_models_from_component(component, composition)
    add_model_from_components component.components, composition
    component.models.each do |name, schema|
      model = models.new name: name, schema: schema
      model.model_compositions.create(composition: composition) if model.save
    end
  end

  def add_model_from_components(components, composition)
    components.each do |component|
      add_models_from_component component, composition
    end
  end

  def count_all_components(comps)
    total = comps.size
    comps.each do |component|
      total += count_all_components component.components
    end
    total
  end

  def set_uid
    self.uid = SecureRandom.uuid.split("-").join ""
  end
end

app/controllers/backend_apps_controller.rb
class BackendAppsController < ApplicationController
  include BackendAppFindable

  before_action :require_login
  before_action :find_app, only: %i(documentation edit show status update)

  def create
    @app = current_user.apps.new permitted
    if @app.save
      flash[:success] = "App successfully created"
      redirect_to backend_app_path @app
    else
      @errors = stringify_single_error @app.errors
      render "new"
    end
  end

  def documentation
    @access_token = @app.access_tokens.where(user_id: current_user.id)
                                      .most_recent
    @models = @app.models.order name: :asc
  end

  def edit
  end

  def index
    @apps = current_user.apps.order(name: :asc).decorate
  end

  def new
    @app = current_user.apps.new
  end

  def show
    @components_count = @app.components_count
    @models_count     = @app.models.size
  end

  def status
    @completed = features.completed.order(completed_at: :desc).limit(3).decorate
    @incompleted = features.incompleted.order(created_at: :asc).decorate
    @status = @incompleted.present? ? "Adding new features" : "Ready for use"
  end

  def update
    if @app.update permitted
      flash[:success] = "Update succeeded"
      redirect_to backend_app_path(@app)
    else
      @errors = stringify_single_error @app.errors
      render "edit"
    end
  end

  private

  def features
    @app.features
  end

  def permitted_params
    %i(description name)
  end
end

app/views/backend_apps/descriptions.html.haml
.content__body
  %h3
    Tell us about the features of "#{@app.name}"
  .content__body__list
    %p
      Use a single sentence to describe each feature, for example:
    %ul{ type: "circle" }
      %li
        %p
          Parents can rent cats or dogs by the hour from pet stores
      %li
        %p
          Pet stores have a directory of all the cats and dogs for rent
      %li
        %p
          Each cat or dog has a name, an hourly rate, and reviews
      %li
        %p
          A review is written by the parent for the cat or dog
    .form
      - if @errors
        .form__errors
          %p
            = @errors
      = form_tag describe_backend_app_path @app do
        = hidden_field_tag :backend_app_id, @app.id
        .form__field
          = text_area_tag :descriptions, "",
            class: "form__textarea--width",
            placeholder: "Describe your features here..."
        = button_tag "Save Features", class: "form__button"

app/views/backend_apps/documentation.html.haml
= content_for :page_title, "Documentation"

.content__body
  %h3
    = render "backend_apps/shared/breadcrumbs"
    Documentation
  %p
    All API is accessed via the https://api.firebot.io domain

.content__body
  %h3
    Headers
  %p
    With each request, add these in your header
  .content__body__list
    %ul{ type: "circle" }
      %li
        %p
          X-Firebot-Application-Id
          \-
          = @app.uid
      %li
        %p
          X-Firebot-Application-Key
          \-
          = @access_token.try :token
      %li
        %p
          Content-Type
          \-
          application/json

- @models.each do |model|
  .content__body
    %h3
      = model.name
    %table
      %tr
        %td
          URL
        %td
          HTTP Verb
        %td
          Functionality
      %tr
        %td
          = "/1/objects/#{model.name}"
        %td
          GET
        %td
          Query multiple #{model.name} objects
      %tr
        %td
          = "/1/objects/#{model.name}"
        %td
          POST
        %td
          Create a new #{model.name}
      %tr
        %td
          = "/1/objects/#{model.name}/<#{model.name}_ID>"
        %td
          GET
        %td
          Retrieve a single #{model.name} object
      %tr
        %td
          = "/1/objects/#{model.name}/<#{model.name}_ID>"
        %td
          PATCH or PUT
        %td
          Update a single #{model.name} object
      %tr
        %td
          = "/1/objects/#{model.name}/<#{model.name}_ID>"
        %td
          DELETE
        %td
          Delete a single #{model.name} object

app/views/backend_apps/edit.html.haml
= content_for :page_title, "Edit #{@app.name}"

= content_for :backend_app_fields_header do
  = render "backend_apps/shared/breadcrumbs"
  Edit

= content_for :backend_app_fields_button do
  Update

= content_for :backend_app_fields_cancel do
  = link_to "Cancel", backend_app_path(@app), class: "form__button--gray"

= render "backend_apps/shared/fields"

app/views/backend_apps/index.html.haml
= content_for :page_title, "Apps"

.content__body
  %h3
    Apps
  - if @apps.present?
    .content__body__list
      %p
        Create a
        = link_to "new app", new_backend_app_path
      %ul{ type: "circle" }
        - @apps.each do |app|
          %li
            %p
              = link_to app.name, app
              \-
              %i
                = app.description
  - else
    %p
      You have no apps, create a
      = link_to "new app", new_backend_app_path

app/views/backend_apps/new.html.haml
= content_for :page_title, "New App"

= content_for :backend_app_fields_header do
  = link_to "Apps", backend_apps_path
  \-
  Create a new app

= content_for :backend_app_fields_button do
  Create App

= content_for :backend_app_fields_cancel do
  = link_to "Cancel", backend_apps_path, class: "form__button--gray"

= render "backend_apps/shared/fields"

app/views/backend_apps/show.html.haml
= content_for :page_title, @app.name

.content__body
  %h3
    = link_to "Apps", backend_apps_path
    \-
    = @app.name
  %p
    - if @app.description.present?
      = @app.description
  .content__body__list
    %ul{ type: "circle" }
      %li
        %p
          = link_to "Components", backend_app_components_path(@app)
          (#{@components_count})
      %li
        %p
          = link_to "Models", backend_app_models_path(@app)
          (#{@models_count})
      %li
        %p
          = link_to "Documentation", documentation_backend_app_path(@app)
      %li
        %p
          = link_to "Settings", edit_backend_app_path(@app)

app/views/backend_apps/status.html.haml
= content_for :page_title, "Status"

.content__body
  %h3
    Status for
    <span class="font-weight-medium">#{@app.name}</span> -
    #{@status}
  - if @incompleted.present?
    .content__body__list
      %p
        The following features are being added:
      %ol
        - @incompleted.each do |feature|
          %li
            %p
              #{feature.created_at} - #{feature.description}
    - if @completed.present?
      .content__body__list
        %p
          Recently added features:
        %ol
          - @completed.each do |feature|
            %li
              %p
                %span.green-dark
                  #{feature.completed_at} - #{feature.description}
    .content__body__list
      %p
        We will notify you when your app is ready, in the meantime:
      %ul
        %li
          %p
            View the details of
            = link_to "your app", backend_app_path(@app)
        %li
          %p
            Add
            = link_to "more features", new_backend_app_feature_path(@app)
        %li
          %p
            Create a
            = link_to "new app", new_backend_app_path
        %li
          %p
            Add a
            = link_to "payment method", "#"
  - else
    %p
      = link_to "Go to app", "#"